apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-with-otel-sidecar.fullname" . }}
  labels:
    {{- include "nginx-with-otel-sidecar.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nginx-with-otel-sidecar.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-with-otel-sidecar.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: nginx
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: nginx-config
              mountPath: /opt/bitnami/nginx/conf/server_blocks
              subPath: server_block.conf
            {{- if .Values.extraVolumeMounts }}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
        {{- if .Values.otel.enabled }}
        - name: otel-collector
          image: {{ .Values.otel.image.registry }}/{{ .Values.otel.image.repository }}:{{ .Values.otel.image.tag }}
          command:
            - /otelcol-contrib
            - --config=/etc/otel/config.yaml
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel
            - name: logs
              mountPath: /var/log/nginx
        {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "nginx-with-otel-sidecar.fullname" . }}
            items:
              - key: server_block.conf
                path: server_block.conf
        - name: otel-config
          configMap:
            name: {{ include "nginx-with-otel-sidecar.fullname" . }}-otel
            items:
              - key: config.yaml
                path: config.yaml
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}