apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-with-otel-sidecar.fullname" . }}-otel
  labels:
    {{- include "nginx-with-otel-sidecar.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.otel.config | indent 4 }}